### ISSUE TITLE
Patch fixing needed. Server crashing over time.

### ISSUE THREAD

**Issue by VallenFrostweaver** [DArkHekRoMaNT/StoneQuarry#1]
Vintage Story 1.16.3
Stone Quarry 1.6.1

I am running a modded server with the below listed mods. I am getting a crash on occasion and it seems to be asking for patches to mods that I am not using? I'm not sure. Either way, the crash reports/logs are here:
[https://www.toptal.com/developers/hastebin/qopuvekowi.yaml](https://www.toptal.com/developers/hastebin/qopuvekowi.yaml)
[https://www.toptal.com/developers/hastebin/ipejebojew.yaml](https://www.toptal.com/developers/hastebin/ipejebojew.yaml)

Modlist:
Better Crates
Bricklayers
Carry Capacity
Cottage Window
DS Debarked Logs
More Roads
Player Corpse
Primitive Survival
Spyglass
Stone Quarry
Th3 Essentials
Workbench Expansion

**Comment by DArkHekRoMaNT** [comment]
These patches just don't work because the condition is not met (more metals mod installed), which it writes about at the end of the patch: "Unmet DependsOn condition (moremetals)". What crash do you have? It's not in the logs.

**Comment by VallenFrostweaver** [comment]
Sorry about that. Here's the Console Crash info: [https://www.toptal.com/developers/hastebin/zukoguqasi.yaml](https://www.toptal.com/developers/hastebin/zukoguqasi.yaml)

**Comment by DArkHekRoMaNT** [comment]
> Assertion at lock-free-alloc.c:145, condition `sb_header' not met, function:alloc_sb, Failed to allocate memory for the lock free allocator

Mono OOM error (not related to mods at all). Check this: https://github.com/mono/mono/issues/12947

**Comment by VallenFrostweaver** [comment]
I have reported it to our server host (Akliz) and they are looking into it. Thank you for your assistance. <3
