### ISSUE TITLE
Not working (┬┬﹏┬┬)

### ISSUE THREAD

**Issue by OGCpl** [DArkHekRoMaNT/StoneQuarry#14]
### Mod Version

3.0

### Game Version

1.18.1 and 1.18.2-rc.1

### OS

Windows

### Play mode

Singleplayer

### Problem

![image](https://user-images.githubusercontent.com/132618784/236331308-64047eb8-52e1-4117-acd3-81bdbb632d50.png)

### Mods

```bash
eather with mods or without its the same
```

### Screenshots

![image](https://user-images.githubusercontent.com/132618784/236331456-4de95694-b2a6-485e-a8f8-cd1d76385826.png)

**Comment by DArkHekRoMaNT** [comment]
CommonLib?

**Comment by OGCpl** [comment]
> CommonLib?

yes i got it installed

**Comment by DArkHekRoMaNT** [comment]
You need CommonLib 2.0.4 and game v1.18.2-rc.1 (not lower). If it still doesn't work then I need the log (client-main.txt)

**Comment by OGCpl** [comment]
i had 2.0  ಠ_ಠ  
![image](https://user-images.githubusercontent.com/132618784/236342447-271fbbb8-6778-4fb8-b38e-6dbb5c2dbd40.png) TY for help 😁👍👍👍 love this mod ❤
