### ISSUE TITLE
Need fix JSON lang jp

### ISSUE THREAD

**Issue by CakesTwix** [DArkHekRoMaNT/StoneQuarry#16]
### Mod Version

3.2.1

### Game Version

1.18.6

### OS

Linux

### Play mode

Singleplayer

### Problem

https://github.com/DArkHekRoMaNT/StoneQuarry/blob/master/Assets/stonequarry/lang/ja.json#L2-L5
Interferes with Weblate with import for translation.
For example: https://github.com/SpearAndFang/wildfarmingrevival/commit/88ad379c58a62437c2d3576ae08c7431dbe882c8#diff-3c250e2dc24e2893a07f3492464f894d9fd32f5012270a4ccfe0ad9be9014ff6L2-L5

**Comment by DArkHekRoMaNT** [comment]
What? What does this have to do with Weblate? And why don't you just delete it?

I'm sorry, but I'm not ready to support many translation sites, it will be chaos. I take translations from [here](https://crowdin.com/project/vintage-story-mods) or they send them to me via PM. But, most likely, I will take exclusively from Crowdin when I automate this

**Comment by DArkHekRoMaNT** [comment]
And Macoto Hino fixed it in the latest version. But I still don't understand why you need Weblate. This may be a good option, but not when there are two of them

**Comment by CakesTwix** [comment]
I want to be able to update all repositories in my Weblate with one click and quickly translate and send you PRs. 
I personally maintain my own instance for translations and send to developers myself. I only require to fix such errors in JSON.

**Comment by CakesTwix** [comment]
> And Macoto Hino fixed it in the latest version. 

Hmm, problem solved then.
