### ISSUE TITLE
Update from 3.1.4 to 3.1.5 corrupted my world

### ISSUE THREAD

**Issue by Giordy492** [DArkHekRoMaNT/StoneQuarry#17]
### Mod Version

3.1.5

### CommonLib Version

2.2.0

### Game Version

1.18.10 (stable)

### OS

Windows

### Play mode

Singleplayer

### Problem

The latest update (3.1.5) turned all the items of the mod in my world to '?', and they cannot be found neither in the creative menu nor the handbook. Going back to 3.1.4 turned all the stone slabs to the default (it has a cobblestone skin) but turned the tools back to normal.

### Logs

```bash
Client main:
https://pastebin.com/iwR28TXF

Server main:
https://pastebin.com/zXAAiysF
```

### Screenshots

![2023-09-12_23-12-01](https://github.com/DArkHekRoMaNT/StoneQuarry/assets/31859067/1135abb1-c24e-48a9-9aff-38835c9bf503)

**Comment by Giordy492** [comment]
Also, when trying to join a world after going back to 3.1.4 having the 3.1.5 version in the mods folder, even though I have disabled it in the mod manager, crashed the game. Removing the 3.1.5 mod from the mods folder allows me to join (with corrupted stone slabs, as said in the issue).

https://pastebin.com/spBghcWE
![2023-09-12_23-46-37](https://github.com/DArkHekRoMaNT/StoneQuarry/assets/31859067/54940a33-3c06-4e2c-9721-49300d356d6f)

**Comment by DArkHekRoMaNT** [comment]
Do you happen to unzip the mods? Or something else strange? In the last crash, it feels like you loaded the assets of the mod without the mod itself.

In the first case, the game could not load the mod because it was already loaded
> 12.9.2023 23:09:59 [Error] [stonequarry] An exception was thrown when trying to load assembly:
System.IO.FileLoadException: Assembly with same name is already loaded

**Comment by Giordy492** [comment]
No I never unzip the mods, I always only use the 1 click install. 
The crash only happens when both v3.1.4 and v3.1.5 are in the mods folder, even though one of them is disabled.
The first time I joined the world I'm pretty sure I removed the 3.1.4 version, in fact it didn't crash, so I don't think that's the cause of the corruption.

**Comment by DArkHekRoMaNT** [comment]
Hm. Looks related to #18

**Comment by DArkHekRoMaNT** [comment]
> Do you happen to unzip the mods? Or something else strange? In the last crash, it feels like you loaded the assets of the mod without the mod itself.
> 
> In the first case, the game could not load the mod because it was already loaded
> 
> > 12.9.2023 23:09:59 [Error] [stonequarry] An exception was thrown when trying to load assembly:
> > System.IO.FileLoadException: Assembly with same name is already loaded

Update SQ to the new version. Also try clearing the folder with ModsByServer and Cache from %AppData%/VintagestoryData and checking that Mods folder contains only one version of StoneQuarry. The game simply doesn't load the mod correctly. Same goes for #18, I think
