### ISSUE TITLE
Rubble storage guide link in handbook redirects to the wrong guide

### ISSUE THREAD

**Issue by pandapants200** [DArkHekRoMaNT/StoneQuarry#21]
### Mod Version

3.2.1

### CommonLib Version

2.3.0

### Game Version

1.19.3 (Stable)

### OS

Windows

### Play mode

Singleplayer

### Problem

Clicking the rubble storage guide link when viewing the rubble storage info in the handbook redirects to the stone-splitting guide rather than the rubble storage guide.

**Comment by DArkHekRoMaNT** [comment]
Fixed in v3.3.0
