### ISSUE TITLE
Plugs Durability after Server Restart

### ISSUE THREAD

**Issue by Stefanklm** [DArkHekRoMaNT/StoneQuarry#22]
### Mod Version

3.2.1

### CommonLib Version

2.3.7

### Game Version

1.19.7

### OS

Windows

### Play mode

Multiplayer

### Problem

We found a bug with the splitter plugs. If you put them in the mountain and then restart the server, you get the plugs back with full durability afterwards

**Comment by DArkHekRoMaNT** [comment]
Fixed in v3.3.0
