### ISSUE TITLE
Config option for PlugSizeModifier does not work

### ISSUE THREAD

**Issue by Mad-Gnome** [DArkHekRoMaNT/StoneQuarry#23]
### Mod Version

3.2.1

### CommonLib Version

2.3.0

### Game Version

1.19.8

### OS

Windows

### Play mode

Singleplayer

### Problem

Config option doesn't change the range of plugs in game.  Other config options are working great though.  (PlugWorkModifier, EnablePlugDurability, CopperPlugDurability, BronzePlugDurability, IronPlugDurability, SteelPlugDurability) 

I can make a server patch for the plug range and that works fine however.

**Comment by DArkHekRoMaNT** [comment]
Fixed in v3.3.0

**Comment by DArkHekRoMaNT** [comment]
Your patch should still work correctly if you have PlugSizeModifier: 1 in your config
