### ISSUE TITLE
3.3.0 Plugs and Tools gone

### ISSUE THREAD

**Issue by Mad-Gnome** [DArkHekRoMaNT/StoneQuarry#24]
### Mod Version

3.3.0

### CommonLib Version

2.4.0

### Game Version

1.19.8

### OS

Windows

### Play mode

Singleplayer

### Problem

Newest update has a formatting issue causing plugs to disappear, not work, etc.
More detailed lists from other members in posts in the moddb.

The file 'plugandfeather' has the issue.

Specifically this section here, where it's missing the , to end the onshelfTransform section.
	"onshelfTransform": {
		"translation": { "x": 0, "y": -0.25, "z": 0 },
		"rotation": { "x": 0, "y": 9, "z": 0 },
		"scale": 0.5
	}   **//missing the , right here.  Mod works fine when added**
    "searchrangeByType": {
      "*-copper-*": 3,
      "*-tinbronze-*": 4,
      "*-bismuthbronze-*": 4,
      "*-blackbronze-*": 5,
      "*-iron-*": 6,
      "*-meteoriciron-*": 6,
      "*-steel-*": 7,
      "*-admin-*": 128
    }
  },

**Comment by DArkHekRoMaNT** [comment]
Fixed in v3.3.1
