### ISSUE TITLE
Creating a quarry with plugs ignores block reinforcement, not sure about claims though.

### ISSUE THREAD

**Issue by Novocain1** [DArkHekRoMaNT/StoneQuarry#5]
Reproduce: 
1: Reinforce some stone with plug and square
2: Create quarry with plugs and hammer

Suggestion: Make it eat reinforcement levels.

**Comment by DArkHekRoMaNT** [comment]
In 2.0.0-pre.1, I added a claims checking (for some reason, GitHub decided not to mention this in the topic, although I indicated #5 in the releases)

**Comment by DArkHekRoMaNT** [comment]
Fixed in 3.0.0
