### ISSUE TITLE
[1.16.5] empty slab

### ISSUE THREAD

**Issue by Jezrai** [DArkHekRoMaNT/StoneQuarry#6]
not sure what happened here, was breaking slabs into stones and the last one didn't vanish
![image](https://user-images.githubusercontent.com/101936623/159124923-861d815e-dcda-4cef-8a5a-e2609e9b9d2e.png)

latest version, with 1.16.4 stable VS

**Comment by Jezrai** [comment]
reloaded the game and it had 1 in it so I was able to finish breaking into stones

**Comment by DArkHekRoMaNT** [comment]
SQ v1.6.5?

**Comment by Jezrai** [comment]
yes

**Comment by gcook725** [comment]
I think we're having the same issue and I posted this on the ModDB page:
```
I'm running into some sort of issue with stone slabs and their contents. It seems that when you combine like stone slabs in your inventory, the game considers them the same block forever. Once you place a single stone slab and smash it with a rubble hammer, it will begin to consume the stone in the slab, but it will also consume the stone in all other slabs of the same stack that are placed and in your inventory (you can notice that the amount of stone in all other slabs from the same stack that are placed will have their amounts updated). Its like the game considers the slabs the same block, like they're quantumly entangled or something. 

If you keep the slabs in seperate stacks when you place them in the world (taking one slab out of a stack manually inside of your inventory, and then placing that one slab), then they won't be "entangled" in this way and will function as expected.
```

**Comment by DArkHekRoMaNT** [comment]
@gcook725 is this from 2.0.0-pre.1? Quantum entangled slabs. Funny bug :smile:

**Comment by DArkHekRoMaNT** [comment]
I think this problem is no longer relevant.
Stone slabs code was heavily rewritten in 2.0.0, it's a small synchronization issue with the old system, I don't think I'll be fixing it.

@gcook725 Your issue has been moved because does not apply to this problem
