### ISSUE TITLE
2.0.0-pre.2 Slabs are non-functional when tools are used on the block space that they are placed.

### ISSUE THREAD

**Issue by gcook725** [DArkHekRoMaNT/StoneQuarry#8]
Slabs do not function when any of the stone quarry tools are used when aiming at the block they were placed. Some animation is attempted, but not finished and nothing happens. For example, the rubble hammer appears to just twitch in your hand and does nothing. Most noticeable with small slabs since they only take up one block. Larger slabs will work fine, but only if you aim at the spots block spaces they occupy outside of the initial block space it was placed.

Mods: Just vanilla and StoneQuarry

**Comment by DArkHekRoMaNT** [comment]
Fixed in v2.0.0-pre.3
