### ISSUE TITLE
2.0.0-pre.2 Slabs containing different amounts of blocks will stack together when picked up.

### ISSUE THREAD

**Issue by gcook725** [DArkHekRoMaNT/StoneQuarry#9]
Slabs of the same size and stone type but containing a different amount of blocks will stack together. This effectively duplicates the slabs in your inventory. To replicate, create a slab with 27 block (3x3x3) and pick it up, then create a slab with any other amount of blocks that is less than 27 and pick it up. The second slab will become identical to the first slab and stack together.

Mods in use: Just StoneQuarry

**Comment by DArkHekRoMaNT** [comment]
Fixed in 2.0.0-pre.4
